title: Blog de la Maria Padrós Fuentes
email: antoni.silvestre+mpf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog amb poemes i pensaments de la Maria Padrós Fuentes
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Maria Padros Fuentes # add your name
author-pic: ciutat.jpg
about-author: Pàgina on escric els meus poemes i pensaments

# Contact links
email: antoni.silvestre+mpf@gmail.com
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle
twitter: '@_mariapadros_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
